-- ============================================================================
-- COMPLETE PENDING MIGRATIONS - All Missing Fields and Tables
-- Date: 2026-02-17
-- Description: Comprehensive migration for all pending schema changes
-- PostgreSQL Production Ready - Idempotent (safe to run multiple times)
-- ============================================================================

-- ============================================================================
-- PART 1: Product Features (IsActive, Barcode, CategoryId, ImageUrl)
-- ============================================================================

-- Add IsActive field to Products (Soft Delete Support)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'Products' AND column_name = 'IsActive'
    ) THEN
        ALTER TABLE "Products" 
        ADD COLUMN "IsActive" boolean NOT NULL DEFAULT true;
        RAISE NOTICE 'Added IsActive column to Products table';
    ELSE
        RAISE NOTICE 'IsActive column already exists, skipping';
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_Products_IsActive" ON "Products" ("IsActive");
UPDATE "Products" SET "IsActive" = true WHERE "IsActive" IS NULL;

-- Add Barcode field to Products
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'Products' AND column_name = 'Barcode'
    ) THEN
        ALTER TABLE "Products" 
        ADD COLUMN "Barcode" character varying(100) NULL;
        RAISE NOTICE 'Added Barcode column to Products table';
    ELSE
        RAISE NOTICE 'Barcode column already exists, skipping';
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_Products_Barcode" ON "Products" ("Barcode");

-- Create unique index on Barcode per tenant
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes 
        WHERE indexname = 'IX_Products_TenantId_Barcode'
    ) THEN
        CREATE UNIQUE INDEX "IX_Products_TenantId_Barcode" 
        ON "Products" ("TenantId", "Barcode") 
        WHERE "Barcode" IS NOT NULL;
        RAISE NOTICE 'Created unique index on Products (TenantId, Barcode)';
    ELSE
        RAISE NOTICE 'Index IX_Products_TenantId_Barcode already exists, skipping';
    END IF;
END $$;

-- Create ProductCategories table
CREATE TABLE IF NOT EXISTS "ProductCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(200) NULL,
    "ColorCode" character varying(7) NOT NULL DEFAULT '#3B82F6',
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id")
);

-- Create unique index on TenantId + Name for ProductCategories
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes 
        WHERE indexname = 'IX_ProductCategories_TenantId_Name'
    ) THEN
        CREATE UNIQUE INDEX "IX_ProductCategories_TenantId_Name" 
        ON "ProductCategories" ("TenantId", "Name");
        RAISE NOTICE 'Created unique index on ProductCategories (TenantId, Name)';
    ELSE
        RAISE NOTICE 'Index IX_ProductCategories_TenantId_Name already exists, skipping';
    END IF;
END $$;

-- Add CategoryId foreign key to Products
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'Products' AND column_name = 'CategoryId'
    ) THEN
        ALTER TABLE "Products" 
        ADD COLUMN "CategoryId" integer NULL;
        RAISE NOTICE 'Added CategoryId column to Products table';
    ELSE
        RAISE NOTICE 'CategoryId column already exists, skipping';
    END IF;
END $$;

-- Create foreign key constraint
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'FK_Products_ProductCategories_CategoryId'
    ) THEN
        ALTER TABLE "Products"
        ADD CONSTRAINT "FK_Products_ProductCategories_CategoryId"
        FOREIGN KEY ("CategoryId") REFERENCES "ProductCategories" ("Id")
        ON DELETE SET NULL;
        RAISE NOTICE 'Created foreign key constraint FK_Products_ProductCategories_CategoryId';
    ELSE
        RAISE NOTICE 'Foreign key constraint FK_Products_ProductCategories_CategoryId already exists, skipping';
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_Products_CategoryId" ON "Products" ("CategoryId");

-- Add ImageUrl field to Products
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'Products' AND column_name = 'ImageUrl'
    ) THEN
        ALTER TABLE "Products" 
        ADD COLUMN "ImageUrl" character varying(500) NULL;
        RAISE NOTICE 'Added ImageUrl column to Products table';
    ELSE
        RAISE NOTICE 'ImageUrl column already exists, skipping';
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_Products_ImageUrl" 
ON "Products" ("ImageUrl") 
WHERE "ImageUrl" IS NOT NULL;

-- ============================================================================
-- VERIFICATION: Check all Product columns exist
-- ============================================================================
DO $$
DECLARE
    missing_columns text[];
BEGIN
    SELECT array_agg(col) INTO missing_columns
    FROM (
        SELECT 'IsActive' AS col WHERE NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'Products' AND column_name = 'IsActive'
        )
        UNION ALL
        SELECT 'Barcode' WHERE NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'Products' AND column_name = 'Barcode'
        )
        UNION ALL
        SELECT 'CategoryId' WHERE NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'Products' AND column_name = 'CategoryId'
        )
        UNION ALL
        SELECT 'ImageUrl' WHERE NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'Products' AND column_name = 'ImageUrl'
        )
    ) missing;
    
    IF array_length(missing_columns, 1) > 0 THEN
        RAISE EXCEPTION 'Missing columns: %', array_to_string(missing_columns, ', ');
    ELSE
        RAISE NOTICE '✅ All product columns verified successfully';
    END IF;
END $$;

-- ============================================================================
-- VERIFICATION: Check ProductCategories table exists
-- ============================================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'ProductCategories'
    ) THEN
        RAISE EXCEPTION 'ProductCategories table was not created';
    ELSE
        RAISE NOTICE '✅ ProductCategories table verified successfully';
    END IF;
END $$;

-- ============================================================================
-- PART: Expenses VatInclusive (persist VAT-inclusive flag per expense)
-- ============================================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'Expenses' AND column_name = 'VatInclusive'
    ) THEN
        ALTER TABLE "Expenses" ADD COLUMN "VatInclusive" boolean NULL;
        RAISE NOTICE 'Added VatInclusive column to Expenses table';
    ELSE
        RAISE NOTICE 'VatInclusive column already exists on Expenses, skipping';
    END IF;
END $$;

-- ============================================================================
-- FINAL SUMMARY
-- ============================================================================
DO $$
BEGIN
    RAISE NOTICE '============================================================================';
    RAISE NOTICE '✅ ALL PENDING MIGRATIONS COMPLETED SUCCESSFULLY';
    RAISE NOTICE '============================================================================';
    RAISE NOTICE 'Product Features Added:';
    RAISE NOTICE '  - IsActive (boolean, default true)';
    RAISE NOTICE '  - Barcode (varchar(100), nullable)';
    RAISE NOTICE '  - CategoryId (integer, nullable FK)';
    RAISE NOTICE '  - ImageUrl (varchar(500), nullable)';
    RAISE NOTICE '';
    RAISE NOTICE 'New Table Created:';
    RAISE NOTICE '  - ProductCategories';
    RAISE NOTICE '============================================================================';
END $$;
